### ISSUE TITLE
Suggestion: Breaking up components to different files

### ISSUE THREAD

**Issue by geekwise-deidra-wallert** [geekwise-yuki-xiong/django-drf-react-bank#12]
This would cut down on the amount of code in the App.js file and might make for easier readability

**Comment by geekwise-yuki-xiong** [comment]
I did not break my App.js file down but kept it the same as it because it was already working and will be expensive to tether with. However, I did convert my react over to utilize routes and components. That huge code is now a component called Models.js and I might never need to add more code to it again. Thanks.
